stages:
  - test

test:
  stage: test
  only:
    - master
    - develop
  script:
    - docker build -t hub.gosun.cloud/gosun/dama-server:demo .
    - docker push hub.gosun.cloud/gosun/dama-server:demo
  tags:
    - other-staging
